# Generated by Django 2.2.2 on 2019-06-15 18:20

from django.db import migrations
from services.models import Category


def create_default_category(apps, schema_editor):
    Category.objects.create(
        name="Маникюр и Педикюр"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190615_2114'),
    ]

    operations = [
        migrations.RunPython(create_default_category)
    ]
