# Generated by Django 2.2.2 on 2019-06-15 18:28

from django.db import migrations, models
import django.db.models.deletion
from services.models import Category


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190615_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(
                default=Category.objects.first().id,
                on_delete=django.db.models.deletion.CASCADE,
                to='services.Category'),
            preserve_default=False,
        ),
    ]
